version: '3'
services:
  php:
    build:
      context: ./php
      args:
        USER: ${USER}
    container_name: php
    volumes:
    - $PWD:/code
  web:
    image: nginx
    container_name: nginx
    ports:
    - "8080:80"
    volumes:
    - $PWD:/code
    - $PWD/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: guest